## Build sila from source from a local directory called go-sila.

FROM golang:1-alpine as builder
RUN apk add --update bash curl jq git make gcc libc-dev linux-headers

# Default local client path: clients/go-sila/<go-sila>
ARG local_path=go-sila

# Copy go.mod and go.sum and download dependencies in a separate layer
COPY $local_path/go.mod $local_path/go.sum go-sila/
RUN cd go-sila && go mod download

# Copy the source code
COPY $local_path go-sila
WORKDIR go-sila
RUN make sila
RUN mv ./build/bin/sila /usr/local/bin/sila

FROM alpine:latest
RUN apk add --update bash curl jq
COPY --from=builder /usr/local/bin/sila /usr/local/bin/sila

# Generate the version.txt file.
RUN /usr/local/bin/sila console --exec 'console.log(admin.nodeInfo.name)' --maxpeers=0 --nodiscover --dev 2>/dev/null | head -1 > /version.txt

# Inject the startup script.
ADD sila.sh /sila.sh
ADD mapper.jq /mapper.jq
RUN chmod +x /sila.sh

# Inject the enode id retriever script.
RUN mkdir /hive-bin
ADD enode.sh /hive-bin/enode.sh
RUN chmod +x /hive-bin/enode.sh

# Add a default genesis file.
ADD genesis.json /genesis.json

# Export the usual networking ports to allow outside access to the node
EXPOSE 8545 8546 8547 8551 30303 30303/udp

ENTRYPOINT ["/sila.sh"]
