### Build Silajs Locally:
### Requires a copy of silajs-monorepo/ -> hive/clients/silajs/

FROM node:20-alpine

RUN apk update && apk add --no-cache bash git jq curl python3 gcc make g++ \
    && rm -rf /var/cache/apk/*

RUN npm i -g ts-node

# Default local client path: clients/silajs/<silajs-monorepo>
ARG local_path=silajs-monorepo

COPY ${local_path}/config silajs-monorepo/config
COPY ${local_path}/package-lock.json silajs-monorepo/package-lock.json
COPY ${local_path}/package.json silajs-monorepo/package.json
COPY ${local_path}/scripts silajs-monorepo/scripts

COPY ${local_path}/packages/block/package.json silajs-monorepo/packages/block/package.json
COPY ${local_path}/packages/blockchain/package.json silajs-monorepo/packages/blockchain/package.json
COPY ${local_path}/packages/client/package.json silajs-monorepo/packages/client/package.json
COPY ${local_path}/packages/common/package.json silajs-monorepo/packages/common/package.json
COPY ${local_path}/packages/devp2p/package.json silajs-monorepo/packages/devp2p/package.json
COPY ${local_path}/packages/silash/package.json silajs-monorepo/packages/silash/package.json
COPY ${local_path}/packages/savm/package.json silajs-monorepo/packages/savm/package.json
COPY ${local_path}/packages/genesis/package.json silajs-monorepo/packages/genesis/package.json
COPY ${local_path}/packages/rlp/package.json silajs-monorepo/packages/rlp/package.json
COPY ${local_path}/packages/statemanager/package.json silajs-monorepo/packages/statemanager/package.json
COPY ${local_path}/packages/mpt/package.json silajs-monorepo/packages/mpt/package.json
COPY ${local_path}/packages/tx/package.json silajs-monorepo/packages/tx/package.json
COPY ${local_path}/packages/util/package.json silajs-monorepo/packages/util/package.json
COPY ${local_path}/packages/verkle/package.json silajs-monorepo/packages/verkle/package.json
COPY ${local_path}/packages/vm/package.json silajs-monorepo/packages/vm/package.json
COPY ${local_path}/packages/wallet/package.json silajs-monorepo/packages/wallet/package.json

# for npm run prepare
RUN cd silajs-monorepo && git init

RUN cd silajs-monorepo && cp package.json package.json.bak && npm pkg set scripts.postinstall="echo no-postinstall"
RUN cd silajs-monorepo && npm i
RUN cd silajs-monorepo && cp package.json.bak package.json && rm package.json.bak

COPY ${local_path}/node_modules/@silajs silajs-monorepo/node_modules/@silajs

COPY ${local_path}/packages/rlp silajs-monorepo/packages/rlp
COPY ${local_path}/packages/util silajs-monorepo/packages/util
COPY ${local_path}/packages/verkle silajs-monorepo/packages/verkle
COPY ${local_path}/packages/wallet silajs-monorepo/packages/wallet
COPY ${local_path}/packages/common silajs-monorepo/packages/common
COPY ${local_path}/packages/devp2p silajs-monorepo/packages/devp2p
COPY ${local_path}/packages/genesis silajs-monorepo/packages/genesis
COPY ${local_path}/packages/mpt silajs-monorepo/packages/mpt
COPY ${local_path}/packages/statemanager silajs-monorepo/packages/statemanager
COPY ${local_path}/packages/tx silajs-monorepo/packages/tx
COPY ${local_path}/packages/savm silajs-monorepo/packages/savm
COPY ${local_path}/packages/block silajs-monorepo/packages/block
COPY ${local_path}/packages/silash silajs-monorepo/packages/silash
COPY ${local_path}/packages/blockchain silajs-monorepo/packages/blockchain
COPY ${local_path}/packages/vm silajs-monorepo/packages/vm

RUN cd silajs-monorepo/packages/client && cp package.json package.json.bak && npm pkg set scripts.build="echo no-build"
RUN cd silajs-monorepo && npm run build --workspaces

COPY ${local_path}/packages/client silajs-monorepo/packages/client

# Create version.txt
RUN cd silajs-monorepo/packages/client && npm silajs --version > /version.txt

# Add genesis mapper script, startup script, and enode URL retriever script
ADD genesis.json /genesis.json
ADD mapper.jq /mapper.jq
ADD silajs-local.sh /silajs-local.sh
ADD enode.sh /hive-bin/enode.sh
ADD jwtsecret /jwtsecret

# Set execute permissions for scripts
RUN chmod +x /silajs-local.sh /hive-bin/enode.sh

# Expose networking ports
EXPOSE 8545 8546 8551 8547 30303 30303/udp

# NodeJS applications have a default memory limit of 2.5GB.
# This limit is bit tight, it is recommended to raise the limit
# since memory may spike during certain network conditions.
ENV NODE_OPTIONS=--max_old_space_size=6144

ENTRYPOINT ["/silajs-local.sh"]